### ISSUE TITLE
Shovel Problem

### ISSUE THREAD

**Issue by SuperCoder7979** [SuperCoder7979/Planetary-Apocalypse#1]
You have to chop wood again to re create shovel, discovered by Advait Naik.

**Comment by Coder9926** [comment]
Are you wishing to prevent the loss of wood when making a shovel or do you wish that whenever someone makes a shovel they lose wood but have the ability to make a shovel again without losing wood?

**Comment by SuperCoder7979** [comment]
The problem is that once you break a shovel, you must click gather wood again to re-enable the make shovel button, even if you had enough wood to make another one.

**Comment by Coder9926** [comment]
Simple misplacement of a conditional.
