### ISSUE TITLE
"Make bricks" isn't possible even with adequate materials.

### ISSUE THREAD

**Issue by Coder9926** [SuperCoder7979/Planetary-Apocalypse#18]
When forced to become enabled, process works fine.

**Comment by Coder9926** [comment]
![image](https://cloud.githubusercontent.com/assets/7228628/23345964/b82a915c-fc63-11e6-803b-4d4dc5ec7779.png)

**Comment by SuperCoder7979** [comment]
Fixed. I #%*&@$ up a variable name.
